### ISSUE TITLE
Invalid token with Authelia

### ISSUE THREAD

**Issue by rmaziere** [oidc-wp/openid-connect-generic#554]
Hello,

I would like to use Authelia with WordPress, but I have an error at the end of the connection process : **Invalid token**.

What I have :
- an Apache2 web server with WordPress 6.5.5
- the plugin OpenID Connect Generic Client v 3.10.0
- Authelia 

What I did :
Followed the Authelia's guide for WordPress integration : https://www.authelia.com/integration/openid-connect/wordpress/ which recommend using your plugin.
The plugin was installed on WordPress via the plugins' menu, and configured as you can see below.
(the client_key, is the clear password)

![Capture d’écran 2024-07-17 à 14 52 48-fullpage](https://github.com/user-attachments/assets/29167931-d2e7-42ae-bb3d-3e3a0a6045b8)

The Authelia's configuration is :
```yml
[...]
identity_providers:
  oidc:
    hmac_secret: '[...]'
    jwks:
    -
      algorithm: 'RS256'
      use: 'sig'
      key: |
        -----BEGIN PRIVATE KEY-----
        [...]
        -----END PRIVATE KEY-----
    enable_client_debug_messages: true
    clients:
        client_id: 'wordpress_[...]'
        client_name: 'Wordpress'
        client_secret: '$pbkdf2-sha512[...]'
        public: false
        redirect_uris:
          - 'https://www.example.com/wp-admin/admin-ajax.php?action=openid-connect-authorize'
        scopes:
          - 'openid'
          - 'groups'
          - 'email'
          - 'profile'
        authorization_policy: 'one_factor'
        require_pkce: true
        pkce_challenge_method: 'S256'
        token_endpoint_auth_method: 'client_secret_post'
        userinfo_signed_response_alg: 'none'
```

After installation and configuration, this is not working : **Invalid token**.
![Capture d’écran du 2024-07-17 13-01-02](https://github.com/user-attachments/assets/5bb3600d-7cfa-4363-ad79-490d9da9b58e)
![Capture d’écran du 2024-07-17 13-01-28](https://github.com/user-attachments/assets/aac84297-90db-48f7-a0bd-4475c03e5490)
![Capture d’écran du 2024-07-17 13-01-47](https://github.com/user-attachments/assets/c952fe97-5e95-4f37-bb44-51692268433c)

But all seems to be ok on the Authlia side :
```log
Authorization Request with id 'ae007303-xxxxx' on client with id 'wordpress_xxx' is being processed" method=GET path=/api/oidc/authorize remote_ip=xx.client_ip.xx
Mark 1FA authentication attempt made by user 'username'" method=POST path=/api/firstfactor remote_ip=xx.client_ip.xx
Successful 1FA authentication attempt made by user 'username'" method=POST path=/api/firstfactor remote_ip=xx.client_ip.xx
Authorization Request with id '265d71fd-xxxxx' on client with id 'wordpress_xxx' is being processed" method=GET path=/api/oidc/authorization remote_ip=xx.client_ip.xx
Authorization Request with id '265d71fd-xxxxx' on client with id 'wordpress_xxx' using consent mode 'explicit' proceeding to generate a new consent session" method=GET path=/api/oidc/authorization remote_ip=xx.client_ip.xx
Authorization Request with id '265d71fd-xxxxx' on client with id 'wordpress_xxx' using consent mode 'explicit' authentication level 'one_factor' is sufficient for client level 'one_factor'" method=GET path=/api/oidc/authorization remote_ip=xx.client_ip.xx
Authorization Request with id '265d71fd-xxxxx' on client with id 'wordpress_xxx' using consent mode 'explicit' is being redirected to 'https://auth.example.com/consent?id=6bb95951-xxxxx'" method=GET path=/api/oidc/authorization remote_ip=xx.client_ip.xx
# the consent validation here
Authorization Request with id '61e1667d-xxxxx' on client with id 'wordpress_xxx' is being processed" method=GET path=/api/oidc/authorization remote_ip=xx.client_ip.xx
Authorization Request with id '61e1667d-xxxxx' on client with id 'wordpress_xxx' was successfully processed, proceeding to build Authorization Response" method=GET path=/api/oidc/authorization remote_ip=xx.client_ip.xx
Access Request with id '61e1667d-xxxxx' on client with id 'wordpress_xxx' is being processed" method=POST path=/api/oidc/token remote_ip=xx.wordpress_ip.xx
Access Request with id '61e1667d-xxxxx' on client with id 'wordpress_xxx' **has successfully been processed**" method=POST path=/api/oidc/token remote_ip=xx.wordpress_ip.xx
```
I think the problem is on the wordpress/plugin side.

After reading all doc, tickets and more, I'll be grateful for help.
